services:
  proxy:
    build: .
    command: node reverse_proxy.js
    ports:
      - "5000:5000"
    networks:
      - private-link
    depends_on:
      - mock-backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mock-backend:
    build: .
    command: node servers/server.js
    deploy:
      replicas: 3
    networks:
      - private-link

networks:
  private-link:
    driver: bridge
